CREATE TABLE CLIENT (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(1000)
);

CREATE TABLE PRODUCT (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	description VARCHAR(1000),
	price NUMERIC(20,2)
);

CREATE TABLE PURCHASE(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	client_id INTEGER REFERENCES CLIENT (id),
	purchase_date TIMESTAMP,
	total NUMERIC (20,2)
);

CREATE TABLE PURCHASE_ITEM(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	purchase_id INTEGER REFERENCES PURCHASE (id),
	product_id INTEGER REFERENCES PRODUCT (id),
	qty INTEGER
);